
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "qobzgblhdztldvbghpjo"

[api]
enabled = true
port = 54321
schemes = ["http", "https"]

# [api.static]
# public_dir = "public/static"

[api.headers]
# [api.headers.default]
# X-Frame-Options = "SAMEORIGIN"

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "https://api.supabase.com"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://lovable.dev"
additional_redirect_urls = ["https://lovable.dev/auth/callback"]
jwt_expiry = 3600
enable_signup = true

[analytics]
enabled = false
port = 54327
vector_port = 54328
